<?php
// check_notifications.php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$p_id = $_SESSION['user_id'];

// 1. CHECK FOR NEW PRESCRIPTIONS
// We check if there are prescriptions that don't have a notification yet
$sql_rx = "SELECT * FROM prescriptions WHERE patient_id = '$p_id'";
$res_rx = $conn->query($sql_rx);

while($rx = $res_rx->fetch_assoc()) {
    $rx_id = $rx['prescription_id'];
    
    // Check if notification already exists
    $check = $conn->query("SELECT id FROM notifications WHERE patient_id = '$p_id' AND source_id = '$rx_id' AND type = 'prescription'");
    
    if($check->num_rows == 0) {
        // Insert Notification
        $title = "Prescription Uploaded";
        $msg = "A new prescription has been generated by your doctor.";
        $insert = "INSERT INTO notifications (patient_id, type, title, message, source_id) VALUES ('$p_id', 'prescription', '$title', '$msg', '$rx_id')";
        $conn->query($insert);
    }
}

// 2. CHECK FOR CONFIRMED APPOINTMENTS
$sql_appt = "SELECT * FROM appointments WHERE patient_id = '$p_id' AND status = 'Confirmed'";
$res_appt = $conn->query($sql_appt);

while($appt = $res_appt->fetch_assoc()) {
    $appt_id = $appt['appointment_id'];
    
    // Check if notification already exists
    $check = $conn->query("SELECT id FROM notifications WHERE patient_id = '$p_id' AND source_id = '$appt_id' AND type = 'appointment_confirmed'");
    
    if($check->num_rows == 0) {
        $date = date("d M", strtotime($appt['appointment_date']));
        $time = date("h:i A", strtotime($appt['appointment_time']));
        $title = "Booking Confirmed";
        $msg = "Your appointment is confirmed for $date at $time.";
        
        $insert = "INSERT INTO notifications (patient_id, type, title, message, source_id) VALUES ('$p_id', 'appointment_confirmed', '$title', '$msg', '$appt_id')";
        $conn->query($insert);
    }

    // 3. CHECK FOR MEETING LINKS (If doctor added a link)
    if(!empty($appt['meeting_link'])) {
        $check_link = $conn->query("SELECT id FROM notifications WHERE patient_id = '$p_id' AND source_id = '$appt_id' AND type = 'meeting_link'");
        
        if($check_link->num_rows == 0) {
            $title = "Meeting Link Added";
            $msg = "Dr. has added a video link for your upcoming consultation.";
            $insert = "INSERT INTO notifications (patient_id, type, title, message, source_id) VALUES ('$p_id', 'meeting_link', '$title', '$msg', '$appt_id')";
            $conn->query($insert);
        }
    }
}

// 4. GET UNREAD COUNT
$sql_count = "SELECT COUNT(*) as unread FROM notifications WHERE patient_id = '$p_id' AND is_read = 0";
$res_count = $conn->query($sql_count);
$count_data = $res_count->fetch_assoc();
$unread_count = $count_data['unread'];
?>